// <auto-generated />
using System;
using ITAM.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITAM.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ITAM.Domain.Entities.Catalogs.DMTaiSan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("DMTaiSan");
                });

            modelBuilder.Entity("ITAM.Domain.Entities.Catalogs.HangHoa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("DMTaiSanId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HangSanXuat")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("RequireSerial")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DMTaiSanId");

                    b.ToTable("HangHoa", (string)null);
                });

            modelBuilder.Entity("ITAM.Domain.Entities.Catalogs.LoaiTaiSan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("MaxValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("LoaiTaiSan");
                });

            modelBuilder.Entity("ITAM.Domain.Entities.Catalogs.NhaCungCap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("NhaCungCap");
                });

            modelBuilder.Entity("ITAM.Domain.Entities.Catalogs.PhongBan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("PhongBan");
                });

            modelBuilder.Entity("ITAM.Domain.Entities.Catalogs.ViTriTaiSan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("PhongBanId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PhongBanId");

                    b.ToTable("ViTriTaiSan");
                });

            modelBuilder.Entity("ITAM.Domain.Entities.DieuChuyen", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayDuyet")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<long?>("NguoiDuyetId")
                        .HasColumnType("bigint");

                    b.Property<string>("NguoiGiao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NguoiNhan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("NguoiTaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("PhongBanChuyenDenId")
                        .HasColumnType("bigint");

                    b.Property<long>("PhongBanChuyenDiId")
                        .HasColumnType("bigint");

                    b.Property<string>("SoPhieu")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDuyetId");

                    b.HasIndex("NguoiTaoId");

                    b.HasIndex("PhongBanChuyenDenId");

                    b.HasIndex("PhongBanChuyenDiId");

                    b.HasIndex("SoPhieu")
                        .IsUnique();

                    b.ToTable("DieuChuyen");
                });

            modelBuilder.Entity("ITAM.Domain.Entities.DieuChuyenChiTiet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("DieuChuyenId")
                        .HasColumnType("bigint");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TaiSanDinhDanhId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("ViTriChuyenDenId")
                        .HasColumnType("bigint");

                    b.Property<long>("ViTriChuyenDiId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DieuChuyenId");

                    b.HasIndex("TaiSanDinhDanhId");

                    b.HasIndex("ViTriChuyenDenId");

                    b.HasIndex("ViTriChuyenDiId");

                    b.ToTable("DieuChuyenChiTiet");
                });

            modelBuilder.Entity("ITAM.Domain.Entities.Identity.Feature", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Features");
                });

            modelBuilder.Entity("ITAM.Domain.Entities.Identity.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("ITAM.Domain.Entities.Identity.RoleFeature", b =>
                {
                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("FeatureId")
                        .HasColumnType("bigint");

                    b.HasKey("RoleId", "FeatureId");

                    b.HasIndex("FeatureId");

                    b.ToTable("RoleFeatures");
                });

            modelBuilder.Entity("ITAM.Domain.Entities.Identity.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<long?>("PhongBanId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PhongBanId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ITAM.Domain.Entities.Identity.UserPhongBan", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("PhongBanId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "PhongBanId");

                    b.HasIndex("PhongBanId");

                    b.ToTable("UserPhongBans", (string)null);
                });

            modelBuilder.Entity("ITAM.Domain.Entities.Identity.UserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("ITAM.Domain.Entities.LichSuDieuChuyenTaiSan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("DieuChuyenChiTietId")
                        .HasColumnType("bigint");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayDuyet")
                        .HasColumnType("datetime2");

                    b.Property<long>("NguoiDuyetId")
                        .HasColumnType("bigint");

                    b.Property<long>("TaiSanDinhDanhId")
                        .HasColumnType("bigint");

                    b.Property<long>("ViTriChuyenDenId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ViTriChuyenDiId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DieuChuyenChiTietId");

                    b.HasIndex("NguoiDuyetId");

                    b.HasIndex("TaiSanDinhDanhId");

                    b.HasIndex("ViTriChuyenDenId");

                    b.HasIndex("ViTriChuyenDiId");

                    b.ToTable("LichSuDieuChuyenTaiSan");
                });

            modelBuilder.Entity("ITAM.Domain.Entities.LoNhap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MaHoaDon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<long?>("NguoiDuyetId")
                        .HasColumnType("bigint");

                    b.Property<string>("NguoiGiao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("NguoiLapPhieuId")
                        .HasColumnType("bigint");

                    b.Property<long>("NhaCungCapId")
                        .HasColumnType("bigint");

                    b.Property<string>("SoLo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDuyetId");

                    b.HasIndex("NguoiLapPhieuId");

                    b.HasIndex("NhaCungCapId");

                    b.HasIndex("SoLo")
                        .IsUnique();

                    b.ToTable("LoNhap", (string)null);
                });

            modelBuilder.Entity("ITAM.Domain.Entities.LoNhapChiTiet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("HangHoaId")
                        .HasColumnType("bigint");

                    b.Property<long>("LoNhapId")
                        .HasColumnType("bigint");

                    b.Property<long>("LoaiTaiSanId")
                        .HasColumnType("bigint");

                    b.Property<string>("SoLo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SoLuongNhap")
                        .HasColumnType("int");

                    b.Property<string>("TenVatPham")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("HangHoaId");

                    b.HasIndex("LoNhapId");

                    b.HasIndex("LoaiTaiSanId");

                    b.HasIndex("SoLo")
                        .IsUnique();

                    b.ToTable("LoNhapChiTiet", (string)null);
                });

            modelBuilder.Entity("ITAM.Domain.Entities.TaiSanDinhDanh", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GiaNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("HangHoaId")
                        .HasColumnType("bigint");

                    b.Property<long>("LoNhapChiTietId")
                        .HasColumnType("bigint");

                    b.Property<long>("LoaiTaiSanId")
                        .HasColumnType("bigint");

                    b.Property<int?>("NamSuDung")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Serial")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThaiTaiSan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("ViTriTaiSanId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("HangHoaId");

                    b.HasIndex("LoNhapChiTietId");

                    b.HasIndex("LoaiTaiSanId");

                    b.HasIndex("Serial");

                    b.HasIndex("ViTriTaiSanId");

                    b.ToTable("TaiSanDinhDanh", (string)null);
                });

            modelBuilder.Entity("VatTu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("DonViTinh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("HangHoaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("ViTriTaiSanId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("HangHoaId")
                        .IsUnique();

                    b.HasIndex("ViTriTaiSanId");

                    b.ToTable("VatTu", (string)null);
                });

            modelBuilder.Entity("ITAM.Domain.Entities.Catalogs.HangHoa", b =>
                {
                    b.HasOne("ITAM.Domain.Entities.Catalogs.DMTaiSan", "DMTaiSan")
                        .WithMany()
                        .HasForeignKey("DMTaiSanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DMTaiSan");
                });

            modelBuilder.Entity("ITAM.Domain.Entities.Catalogs.ViTriTaiSan", b =>
                {
                    b.HasOne("ITAM.Domain.Entities.Catalogs.PhongBan", "PhongBan")
                        .WithMany("ViTriTaiSans")
                        .HasForeignKey("PhongBanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("ITAM.Domain.Entities.DieuChuyen", b =>
                {
                    b.HasOne("ITAM.Domain.Entities.Identity.User", "NguoiDuyet")
                        .WithMany()
                        .HasForeignKey("NguoiDuyetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ITAM.Domain.Entities.Identity.User", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("NguoiTaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ITAM.Domain.Entities.Catalogs.PhongBan", "PhongBanChuyenDen")
                        .WithMany()
                        .HasForeignKey("PhongBanChuyenDenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ITAM.Domain.Entities.Catalogs.PhongBan", "PhongBanChuyenDi")
                        .WithMany()
                        .HasForeignKey("PhongBanChuyenDiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiDuyet");

                    b.Navigation("NguoiTao");

                    b.Navigation("PhongBanChuyenDen");

                    b.Navigation("PhongBanChuyenDi");
                });

            modelBuilder.Entity("ITAM.Domain.Entities.DieuChuyenChiTiet", b =>
                {
                    b.HasOne("ITAM.Domain.Entities.DieuChuyen", "DieuChuyen")
                        .WithMany("ChiTiets")
                        .HasForeignKey("DieuChuyenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITAM.Domain.Entities.TaiSanDinhDanh", "TaiSanDinhDanh")
                        .WithMany()
                        .HasForeignKey("TaiSanDinhDanhId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ITAM.Domain.Entities.Catalogs.ViTriTaiSan", "ViTriChuyenDen")
                        .WithMany()
                        .HasForeignKey("ViTriChuyenDenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ITAM.Domain.Entities.Catalogs.ViTriTaiSan", "ViTriChuyenDi")
                        .WithMany()
                        .HasForeignKey("ViTriChuyenDiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DieuChuyen");

                    b.Navigation("TaiSanDinhDanh");

                    b.Navigation("ViTriChuyenDen");

                    b.Navigation("ViTriChuyenDi");
                });

            modelBuilder.Entity("ITAM.Domain.Entities.Identity.RoleFeature", b =>
                {
                    b.HasOne("ITAM.Domain.Entities.Identity.Feature", "Feature")
                        .WithMany("RoleFeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITAM.Domain.Entities.Identity.Role", "Role")
                        .WithMany("RoleFeatures")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ITAM.Domain.Entities.Identity.User", b =>
                {
                    b.HasOne("ITAM.Domain.Entities.Catalogs.PhongBan", "PhongBan")
                        .WithMany()
                        .HasForeignKey("PhongBanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("ITAM.Domain.Entities.Identity.UserPhongBan", b =>
                {
                    b.HasOne("ITAM.Domain.Entities.Catalogs.PhongBan", "PhongBan")
                        .WithMany()
                        .HasForeignKey("PhongBanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITAM.Domain.Entities.Identity.User", "User")
                        .WithMany("UserPhongBans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhongBan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ITAM.Domain.Entities.Identity.UserRole", b =>
                {
                    b.HasOne("ITAM.Domain.Entities.Identity.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITAM.Domain.Entities.Identity.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ITAM.Domain.Entities.LichSuDieuChuyenTaiSan", b =>
                {
                    b.HasOne("ITAM.Domain.Entities.DieuChuyenChiTiet", "DieuChuyenChiTiet")
                        .WithMany()
                        .HasForeignKey("DieuChuyenChiTietId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ITAM.Domain.Entities.Identity.User", "NguoiDuyet")
                        .WithMany()
                        .HasForeignKey("NguoiDuyetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ITAM.Domain.Entities.TaiSanDinhDanh", "TaiSanDinhDanh")
                        .WithMany()
                        .HasForeignKey("TaiSanDinhDanhId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ITAM.Domain.Entities.Catalogs.ViTriTaiSan", "ViTriChuyenDen")
                        .WithMany()
                        .HasForeignKey("ViTriChuyenDenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ITAM.Domain.Entities.Catalogs.ViTriTaiSan", "ViTriChuyenDi")
                        .WithMany()
                        .HasForeignKey("ViTriChuyenDiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DieuChuyenChiTiet");

                    b.Navigation("NguoiDuyet");

                    b.Navigation("TaiSanDinhDanh");

                    b.Navigation("ViTriChuyenDen");

                    b.Navigation("ViTriChuyenDi");
                });

            modelBuilder.Entity("ITAM.Domain.Entities.LoNhap", b =>
                {
                    b.HasOne("ITAM.Domain.Entities.Identity.User", "NguoiDuyet")
                        .WithMany()
                        .HasForeignKey("NguoiDuyetId");

                    b.HasOne("ITAM.Domain.Entities.Identity.User", "NguoiLapPhieu")
                        .WithMany()
                        .HasForeignKey("NguoiLapPhieuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ITAM.Domain.Entities.Catalogs.NhaCungCap", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("NhaCungCapId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiDuyet");

                    b.Navigation("NguoiLapPhieu");

                    b.Navigation("NhaCungCap");
                });

            modelBuilder.Entity("ITAM.Domain.Entities.LoNhapChiTiet", b =>
                {
                    b.HasOne("ITAM.Domain.Entities.Catalogs.HangHoa", "HangHoa")
                        .WithMany()
                        .HasForeignKey("HangHoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ITAM.Domain.Entities.LoNhap", "LoNhap")
                        .WithMany("ChiTiets")
                        .HasForeignKey("LoNhapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITAM.Domain.Entities.Catalogs.LoaiTaiSan", "LoaiTaiSan")
                        .WithMany()
                        .HasForeignKey("LoaiTaiSanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("HangHoa");

                    b.Navigation("LoNhap");

                    b.Navigation("LoaiTaiSan");
                });

            modelBuilder.Entity("ITAM.Domain.Entities.TaiSanDinhDanh", b =>
                {
                    b.HasOne("ITAM.Domain.Entities.Catalogs.HangHoa", "HangHoa")
                        .WithMany()
                        .HasForeignKey("HangHoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ITAM.Domain.Entities.LoNhapChiTiet", "LoNhapChiTiet")
                        .WithMany("TaiSanDinhDanhs")
                        .HasForeignKey("LoNhapChiTietId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ITAM.Domain.Entities.Catalogs.LoaiTaiSan", "LoaiTaiSan")
                        .WithMany()
                        .HasForeignKey("LoaiTaiSanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ITAM.Domain.Entities.Catalogs.ViTriTaiSan", "ViTriTaiSan")
                        .WithMany()
                        .HasForeignKey("ViTriTaiSanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HangHoa");

                    b.Navigation("LoNhapChiTiet");

                    b.Navigation("LoaiTaiSan");

                    b.Navigation("ViTriTaiSan");
                });

            modelBuilder.Entity("VatTu", b =>
                {
                    b.HasOne("ITAM.Domain.Entities.Catalogs.HangHoa", "HangHoa")
                        .WithMany()
                        .HasForeignKey("HangHoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ITAM.Domain.Entities.Catalogs.ViTriTaiSan", "ViTriTaiSan")
                        .WithMany()
                        .HasForeignKey("ViTriTaiSanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HangHoa");

                    b.Navigation("ViTriTaiSan");
                });

            modelBuilder.Entity("ITAM.Domain.Entities.Catalogs.PhongBan", b =>
                {
                    b.Navigation("ViTriTaiSans");
                });

            modelBuilder.Entity("ITAM.Domain.Entities.DieuChuyen", b =>
                {
                    b.Navigation("ChiTiets");
                });

            modelBuilder.Entity("ITAM.Domain.Entities.Identity.Feature", b =>
                {
                    b.Navigation("RoleFeatures");
                });

            modelBuilder.Entity("ITAM.Domain.Entities.Identity.Role", b =>
                {
                    b.Navigation("RoleFeatures");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ITAM.Domain.Entities.Identity.User", b =>
                {
                    b.Navigation("UserPhongBans");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ITAM.Domain.Entities.LoNhap", b =>
                {
                    b.Navigation("ChiTiets");
                });

            modelBuilder.Entity("ITAM.Domain.Entities.LoNhapChiTiet", b =>
                {
                    b.Navigation("TaiSanDinhDanhs");
                });
#pragma warning restore 612, 618
        }
    }
}
