<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<Folder Include="Services\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.0.0" />
		<PackageReference Include="Mapster" Version="10.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\ITAM.Domain\ITAM.Domain.csproj" />
	</ItemGroup>

</Project>
